---
name: Build

on:
  push:
    branches: [master]
    paths:
      - 'lib/**'
      - 'test/**'
      - '*.gemspec'
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: [2.7, 3.1, 3.4]
        gemfile: [ar6, ar7, ar8]
        exclude:
          - ruby: 2.7
            gemfile: ar8
          - ruby: 3.2
            gemfile: ar8
          - ruby: 3.4
            gemfile: ar6
    runs-on: ${{ matrix.os }}

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/test/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
